# Exemple à adapter dans votre server { } Nginx (front Angular statique)
# location = /index.html {
#   add_header Cache-Control "no-cache, no-store, must-revalidate";
# }
# location ~* \.(js|css)$ {
#   add_header Cache-Control "public, max-age=31536000, immutable";
# }
