server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    # Redirection slash final (évite 404 sur /pro sans slash)
    location = /pro {
        return 301 /pro/;
    }

    location /pro/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /pro/index.html;
    }

    location = / {
        return 302 /pro/;
    }
}
